name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          npm install
          npm run update
          npm run build

      - name: Commit updated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update and build for release" || echo "No changes to commit"
          git push

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            public/main.js
            public/manifest.json
            public/styles.css
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}