name: Release Obsidian plugin

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Set git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Build plugin
        run: |
          npm run updateversion
          npm install
          npm run build

      - name: Commit updated files
        run: |
          git add .
          git commit -m "chore: update and build for release" || echo "No changes to commit"
          git push

      - name: Tag commit with manifest version
        id: tag
        run: |
          VERSION=$(jq -r .version public/manifest.json)


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.VERSION }}
          files: |
            public/main.js
            public/manifest.json
            public/styles.css
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}